# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='person',
            name='man',
            field=models.BooleanField(default=True),
        ),
    ]
